variables:
  IMAGE_OPENJDK_GRADLE: gradle:7.3.3-jdk11-alpine


stages:
  - clean
  - build
  - test
  - build-image
  - publish-image
  - deploy


clean:
  image: $IMAGE_OPENJDK_GRADLE
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/gradlew clean


build:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Compiling the code..."
    - sh $CI_PROJECT_DIR/gradlew assemble
  artifacts:
    paths:
      - build/libs/doctorspolis-*.war


build-image:
  stage: build-image
  script:
    - echo "Building Docker Image..."
    - docker build -t $CI_REGISTRY/doctorspolis/blog-api:$CI_COMMIT_SHORT_SHA .
    - docker build -t $CI_REGISTRY/doctorspolis/blog-api:latest .


publish-image:
  stage: publish-image
  script:
    - echo "Publishing Docker Image..."
    - docker login -u doctorspolis -p $MJOVANC_CONTAINER_REGISTRY_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/doctorspolis/doctorspolis-api:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/doctorspolis/doctorspolis-api:latest