## Database Properties
spring.datasource.url = jdbc:postgresql://localhost:5432/doctorspolis
spring.datasource.username = postgres
spring.datasource.password = postgres

## Hibernate Properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = create-drop

# Security Properties
security.basic.enable = false
security.ignored = /**

# Server Properties
server.servlet.context-path = /api

# spring.security.basic.enabled=false
# create user doctorspolis_admin with encrypted password 'EhsNqKv5x';
# grant all privileges on database doctorspolis to doctorspolis_admin;