## Database Properties
# spring.datasource.url = jdbc:postgresql://159.65.25.202:5432/doctorspolis
spring.datasource.url = jdbc:postgresql://localhost:5432/doctorspolis
spring.datasource.username = postgres
spring.datasource.password = postgres
## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = none
spring.sql.init.continue-on-error=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always
# Server Properties
server.servlet.context-path=/api
server.error.whitelabel.enabled=false
# spring.resources.add-mappings=false
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
doctorspolis.jwt.secret.key=MIIJKQIBAAKCAgEAjrxKCP8eKDPJkTodb6f98G0T+Ic9HyljdSPmTPO8zMcgg7Rf \
KwDt4daD1jQ4ey66aX+KJCWaTv1ygr4GpwNoxiNCELD4DeCOhWSUXay36yy8NnKc \
3I+OrqG39qc70GdldnNKGvIy39ctMziP7HB1BOlP4MG6f89D/tGo4EH1y5vtWkWn \
U0mbKsJ7QdyOP7b9E63E0ODFMatrOtPXbgKcqtMtf6LH1hPQgFaAVraje//HoXEJ \
6kKsEBKaIL+b68Ku5kEYOsrP1XUuW3A80sqNJHXJbpAP8bYgBcn2cttE0pPIPlqr \
yiyzXAFV7CpGFOZFGnWffyG9X/1LFKWORiq2oDRiOdM2+7DYhyQ836Lvh9vOJ5Hx \
FjA8p7tpfzm3OUrmGvPaX0yqpPy7EaAsYCIZVn/xMMESl6ucknWc/lD2cvGISEhq \
70SGht2/9MbpQmPaIQgDh4/oW9lu+jczv0uVVEqy+TlWTbGLpICIZTKR40fAF1pX \
R+7YIt3RD1UaLi+wm9K6crp5+QtL1oJyMlRUBLN/17wcinR/LCHJk/90BKeTkkxX \
dbfBVpyaAeVVolNj//WgpGIs3mKJvclaTu/T56CQEsIHvOucV672QZoUFo8+lsPg \
QmwFHRa7y4H8GFbSi3nU0gOlj90xe66a6TmUvUn6HjMr9GonKdGhfi/RHy0CAwEA \
AQKCAgBWTHFWzyiklesg60ow4Bkg7FJOyTWjSZrgkDwF+rgD98Eo4D1J+t3Y1aIQ \
OLKNh8sdTgdvo2yQpZw+gDX1dJI8ecTP4q+XdFW3QQCTQoJQplOFd/ZvRDy4SP65 \
GpOHhXxLCZmcgSNRQwAJIAGkqrmVppqtAXSJIf+yaYD5VegOms/+7G4mZTJzv/JV \
98vpqfGJnF6LC9suFL5YawytbtbaUaQIr5qzTHeboLEnvHVL23IPohCkmnr9nMGj \
WzYibSrh/ClyIn1WSeslTc74g46ipLSNLHz3X24tEdb3yqrpxoAjcx66thwbXJNe \
npCQwki1nrg4XWXqS3LBoPdMZTbU7o95MfL0F6eb3TkK5CB9+St/dkLzibKSXonP \
CQEZaMtDtZywqo+lU0Rw8Nx6f6PCokE1Gf3634MF24gDo6aL7EGn85IPQjFXxyco \
O6gqLN+JF9P5jkuRQwGww8z6U2zjLv4cSMAAnqwsqYMJtUbGwh4vtjf6f/7Ani3x \
DceficOE81s2wHUn+ChCQpiWdK5+oI1VFvZoYjmHBrsYHKDVP9d0UBOUcEvvNtoQ \
jDA4v7jJ0xzl5Sf/IQ+jx8AR8ZEy3XqNO1vu1cIJOGNxXdwjrx2ya0SHfl3C4yNs \
2FwAUZEShX4qiuJlh6huPVKRPjGaZCrx9Q4YonIv7z2cSqlc4QKCAQEAxak3XGiH \
mMSLHLbxPwjADC/DpBVOHWAc8ieyH1GScX0MGqZzl0j8qz99PqGg/HwQ2gaGak1l \
MCDLNSE9MHxmO4z0BSAUjSRsFU9vSz4RRlCxL1GKkeeLVXqZoEAiOVl4u7pf7X+1 \
vqhoHI8iZR3OJgFYNTZiVlW6wjkkrxxuNGu4qZ1AuIt+WMeg3wnKz6UQQNZVo5yf \
a89G0FLw1zvHnURLYrdXtmpXG6efquzUQZqvIi5ptx2qB/7UubnZ2A0sn1H/Psc1 \
2w4OjjqKZwyLmd4mEFwqRjbHR4oC29T6NfBe79DTkQXL0uHmajWIpE6m14kXOpZt \
gL6uOU8vzUGzKwKCAQEAuN0JRwWdbQaTOyApOh4SH+CYiLGYIYA0drAQEd44ID3R \
zULEBMTX5vJg0OPU1BC5OwFpTCegluP+djLh+bLAdMUVYQzqm6z8FBAUYFMHoXrS \
rIXW787ji4iJSFoeYvjhvFfIcOvGoTFqQDWBftYNhzlipo1HBhNHNCdMT4Qzv7UN \
zwZI7q3ehSKB9bmYlfdYahu/x+Ya8VAP59sEyyCbGqnoOicXaoSjy4VvDrrZpcDH \
DtdsbauUBHEjunmum9A2SL2ej6Yt8oVMhgHkxyAioquiG07XDnYz5crGJMcUvMJP \
IFBIMli/KyUB7OL7r/obD70e9AkPTqR5hLJeC0crBwKCAQAKBnckXLjj6rQTlMPP \
qqXy+Ek3/Uyk+Mb/ETxbkkuXLfx7LY4XUkBefy3fC1ua8r/4DvSqV5qWQlOMMk9k \
MisNQizuRZ5FOl+xBQJkEpXVtyoFeGFK3S+X+kvocNhLiFozS1SqOxwAu5HsQOZB \
sq1OCCttJ4D9WAPM7hEKQKrmRcBr+enacljKL/Xc2iZLOdgFMdnOHpeHZE/3KP3G \
LOYG9/vK2fm86s/YOzxB8xkg6rOPTENYYkzJcwdfFCoUZzaoLgSALqJwpdnfJOD4 \
MQ6zkyzjD4mlXgnlev6CH99A9Rwblb/lTyHzZDnHkUeI7eRQckeXVSHgscssZPPL \
uVVZAoIBAQCHcaOHfsyuAeBDtLegFkIvSu5XUM9m1DkcMLlFbixvKvwZyO43lEWf \
tzxKMHNSAQLGAa21l18oztk0nulEerxZkcCtP7pw3xg+Vt2nCY6QuJ28u78UKuA6 \
7omvEiArYbB6v1JjscvxdHQloU5EsO5ughQOdXpxMBS+WICnzfPgZPY+FZvADHH5 \
16Oidx4d2oDUFYq5GpXo8kEFHkpvzW725T/5w4R7jb04s4YAI9SthgYSkLGn1Mt5 \
Sa/kw5y0GqR7PTr8gsQtaY78rEyDvL7Dsr7uBSC6Ps6dcaklbxt5hWBWC5wqDy3Z \
nZ7Agjnn4HaNXIJeSHkHpKhIGiufVcBnAoIBAQCbm+ZZqJgd2cR6beG9IoZWyIJE \
jJnfQrdowFvHqzalsCfLqX+wN0BfkV8nu4G/kIAL2vFN06I5nge1hSlXgLA8GHBR \
nrV4/W0NWdcGQu0ZcATwUrxj5ZfkWJFbORnSYFINe2uuVdSdxzp3DlL15Z1mxBKE \
r6zjyJ7nHXpcXS8ySVGmafJ++dBKpfSuRrS6w/7E+u9KWJxW+SWme4e7UxeTdyOW \
YprQJZITRI4OMu+FWLvrNoIZjkAovI6/2wka31gvHEwPwKcqjeJZc8D56xisnNmy \
+uC24RD12e1/c8/RTC7TPhD+XG22M1I00KD1wWF7vOOMAMc+sylzRxWiLsye \

# 15 min = 15 * 60 * 1000 ms = 900000
doctorspolis.jwt.access.expiration.period=604800000
# TODO
# doctorspolis.jwt.access.expiration.period = 900000
# 7 days = 7 * 24 * 60 * 60 * 1000 ms = 604800000
doctorspolis.jwt.refresh.expiration.period=604800000

# spring.security.basic.enabled=false
# create user doctorspolis_admin with encrypted password 'EhsNqKv5x';
# grant all privileges on database doctorspolis to doctorspolis_admin;
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
