INSERT INTO language (id, code, value) VALUES
                                           (1, 'af', 'Afrikaans'),
                                           (2, 'sq', 'Albanian - shqip'),
                                           (3, 'am', 'Amharic - አማርኛ'),
                                           (4, 'ar', 'Arabic - العربية'),
                                           (5, 'an', 'Aragonese - aragonés'),
                                           (6, 'hy', 'Armenian - հայերեն'),
                                           (7, 'ast', 'Asturian - asturianu'),
                                           (8, 'az', 'Azerbaijani - azərbaycan dili'),
                                           (9, 'eu', 'Basque - euskara'),
                                           (10, 'be', 'Belarusian - беларуская'),
                                           (11, 'bn', 'Bengali - বাংলা'),
                                           (12, 'bs', 'Bosnian - bosanski'),
                                           (13, 'br', 'Breton - brezhoneg'),
                                           (14, 'bg', 'Bulgarian - български'),
                                           (15, 'ca', 'Catalan - català'),
                                           (16, 'ckb', 'Central Kurdish - کوردی (دەستنوسی عەرەبی)'),
                                           (17, 'zh', 'Chinese - 中文'),
                                           (18, 'zh-HK', 'Chinese (Hong Kong) - 中文（香港）'),
                                           (19, 'zh-CN', 'Chinese (Simplified) - 中文（简体）'),
                                           (20, 'zh-TW', 'Chinese (Traditional) - 中文（繁體）'),
                                           (21, 'co', 'Corsican'),
                                           (22, 'hr', 'Croatian - hrvatski'),
                                           (23, 'cs', 'Czech - čeština'),
                                           (24, 'da', 'Danish - dansk'),
                                           (25, 'nl', 'Dutch - Nederlands'),
                                           (26, 'en', 'English'),
                                           (27, 'en-AU', 'English (Australia)'),
                                           (28, 'en-CA', 'English (Canada)'),
                                           (29, 'en-IN', 'English (India)'),
                                           (30, 'en-NZ', 'English (New Zealand)'),
                                           (31, 'en-ZA', 'English (South Africa)'),
                                           (32, 'en-GB', 'English (United Kingdom)'),
                                           (33, 'en-US', 'English (United States)'),
                                           (34, 'eo', 'Esperanto - esperanto'),
                                           (35, 'et', 'Estonian - eesti'),
                                           (36, 'fo', 'Faroese - føroyskt'),
                                           (37, 'fil', 'Filipino'),
                                           (38, 'fi', 'Finnish - suomi'),
                                           (39, 'fr', 'French - français'),
                                           (40, 'fr-CA', 'French (Canada) - français (Canada)'),
                                           (41, 'fr-FR', 'French (France) - français (France)'),
                                           (42, 'fr-CH', 'French (Switzerland) - français (Suisse)'),
                                           (43, 'gl', 'Galician - galego'),
                                           (44, 'ka', 'Georgian - ქართული'),
                                           (45, 'de', 'German - Deutsch'),
                                           (46, 'de-AT', 'German (Austria) - Deutsch (Österreich)'),
                                           (47, 'de-DE', 'German (Germany) - Deutsch (Deutschland)'),
                                           (48, 'de-LI', 'German (Liechtenstein) - Deutsch (Liechtenstein)'),
                                           (49, 'de-CH', 'German (Switzerland) - Deutsch (Schweiz)'),
                                           (50, 'el', 'Greek - Ελληνικά'),
                                           (51, 'gn', 'Guarani'),
                                           (52, 'gu', 'Gujarati - ગુજરાતી'),
                                           (53, 'ha', 'Hausa'),
                                           (54, 'haw', 'Hawaiian - ʻŌlelo Hawaiʻi'),
                                           (55, 'he', 'Hebrew - עברית'),
                                           (56, 'hi', 'Hindi - हिन्दी'),
                                           (57, 'hu', 'Hungarian - magyar'),
                                           (58, 'is', 'Icelandic - íslenska'),
                                           (59, 'id', 'Indonesian - Indonesia'),
                                           (60, 'ia', 'Interlingua'),
                                           (61, 'ga', 'Irish - Gaeilge'),
                                           (62, 'it', 'Italian - italiano'),
                                           (63, 'it-IT', 'Italian (Italy) - italiano (Italia)'),
                                           (64, 'it-CH', 'Italian (Switzerland) - italiano (Svizzera)'),
                                           (65, 'ja', 'Japanese - 日本語'),
                                           (66, 'kn', 'Kannada - ಕನ್ನಡ'),
                                           (67, 'kk', 'Kazakh - қазақ тілі'),
                                           (68, 'km', 'Khmer - ខ្មែរ'),
                                           (69, 'ko', 'Korean - 한국어'),
                                           (70, 'ku', 'Kurdish - Kurdî'),
                                           (71, 'ky', 'Kyrgyz - кыргызча'),
                                           (72, 'lo', 'Lao - ລາວ'),
                                           (73, 'la', 'Latin'),
                                           (74, 'lv', 'Latvian - latviešu'),
                                           (75, 'ln', 'Lingala - lingála'),
                                           (76, 'lt', 'Lithuanian - lietuvių'),
                                           (77, 'mk', 'Macedonian - македонски'),
                                           (78, 'ms', 'Malay - Bahasa Melayu'),
                                           (79, 'ml', 'Malayalam - മലയാളം'),
                                           (80, 'mt', 'Maltese - Malti'),
                                           (81, 'mr', 'Marathi - मराठी'),
                                           (82, 'mn', 'Mongolian - монгол'),
                                           (83, 'ne', 'Nepali - नेपाली'),
                                           (84, 'no', 'Norwegian - norsk'),
                                           (85, 'nb', 'Norwegian Bokmål - norsk bokmål'),
                                           (86, 'nn', 'Norwegian Nynorsk - nynorsk'),
                                           (87, 'oc', 'Occitan'),
                                           (88, 'or', 'Oriya - ଓଡ଼ିଆ'),
                                           (89, 'om', 'Oromo - Oromoo'),
                                           (90, 'ps', 'Pashto - پښتو'),
                                           (91, 'fa', 'Persian - فارسی'),
                                           (92, 'pl', 'Polish - polski'),
                                           (93, 'pt', 'Portuguese - português'),
                                           (94, 'pt-BR', 'Portuguese (Brazil) - português (Brasil)'),
                                           (95, 'pt-PT', 'Portuguese (Portugal) - português (Portugal)'),
                                           (96, 'pa', 'Punjabi - ਪੰਜਾਬੀ'),
                                           (97, 'qu', 'Quechua'),
                                           (98, 'ro', 'Romanian - română'),
                                           (99, 'mo', 'Romanian (Moldova) - română (Moldova)'),
                                           (100, 'rm', 'Romansh - rumantsch'),
                                           (101, 'ru', 'Russian - русский'),
                                           (102, 'gd', 'Scottish Gaelic'),
                                           (103, 'sr', 'Serbian - српски'),
                                           (104, 'sh', 'Serbo-Croatian - Srpskohrvatski'),
                                           (105, 'sn', 'Shona - chiShona'),
                                           (106, 'sd', 'Sindhi'),
                                           (107, 'si', 'Sinhala - සිංහල'),
                                           (108, 'sk', 'Slovak - slovenčina'),
                                           (109, 'sl', 'Slovenian - slovenščina'),
                                           (110, 'so', 'Somali - Soomaali'),
                                           (111, 'st', 'Southern Sotho'),
                                           (112, 'es', 'Spanish - español'),
                                           (113, 'es-AR', 'Spanish (Argentina) - español (Argentina)'),
                                           (114, 'es-419', 'Spanish (Latin America) - español (Latinoamérica)'),
                                           (115, 'es-MX', 'Spanish (Mexico) - español (México)'),
                                           (116, 'es-ES', 'Spanish (Spain) - español (España)'),
                                           (117, 'es-US', 'Spanish (United States) - español (Estados Unidos)'),
                                           (118, 'su', 'Sundanese'),
                                           (119, 'sw', 'Swahili - Kiswahili'),
                                           (120, 'sv', 'Swedish - svenska'),
                                           (121, 'tg', 'Tajik - тоҷикӣ'),
                                           (122, 'ta', 'Tamil - தமிழ்'),
                                           (123, 'tt', 'Tatar'),
                                           (124, 'te', 'Telugu - తెలుగు'),
                                           (125, 'th', 'Thai - ไทย'),
                                           (126, 'ti', 'Tigrinya - ትግርኛ'),
                                           (127, 'to', 'Tongan - lea fakatonga'),
                                           (128, 'tr', 'Turkish - Türkçe'),
                                           (129, 'tk', 'Turkmen'),
                                           (130, 'tw', 'Twi'),
                                           (131, 'uk', 'Ukrainian - українська'),
                                           (132, 'ur', 'Urdu - اردو'),
                                           (133, 'ug', 'Uyghur'),
                                           (134, 'uz', 'Uzbek - o‘zbek'),
                                           (135, 'vi', 'Vietnamese - Tiếng Việt'),
                                           (136, 'wa', 'Walloon - wa'),
                                           (137, 'cy', 'Welsh - Cymraeg'),
                                           (138, 'fy', 'Western Frisian'),
                                           (139, 'xh', 'Xhosa'),
                                           (140, 'yi', 'Yiddish'),
                                           (141, 'yo', 'Yoruba - Èdè Yorùbá'),
                                           (142, 'zu', 'Zulu - isiZulu');

INSERT INTO country(id, code, value) VALUES
                                         (1, 'af', 'Afghanistan'),
                                         (2, 'ax', 'Aland Islands'),
                                         (3, 'al', 'Albania'),
                                         (4, 'dz', 'Algeria'),
                                         (5, 'as', 'American Samoa'),
                                         (6, 'ad', 'Andorra'),
                                         (7, 'ao', 'Angola'),
                                         (8, 'ai', 'Anguilla'),
                                         (9, 'aq', 'Antarctica'),
                                         (10, 'ag', 'Antigua and Barbuda'),
                                         (11, 'ar', 'Argentina'),
                                         (12, 'am', 'Armenia'),
                                         (13, 'aw', 'Aruba'),
                                         (14, 'au', 'Australia'),
                                         (15, 'at', 'Austria'),
                                         (16, 'az', 'Azerbaijan'),
                                         (17, 'bs', 'Bahamas'),
                                         (18, 'bh', 'Bahrain'),
                                         (19, 'bd', 'Bangladesh'),
                                         (20, 'bb', 'Barbados'),
                                         (21, 'by', 'Belarus'),
                                         (22, 'be', 'Belgium'),
                                         (23, 'bz', 'Belize'),
                                         (24, 'bj', 'Benin'),
                                         (25, 'bm', 'Bermuda'),
                                         (26, 'bt', 'Bhutan'),
                                         (27, 'bo', 'Bolivia'),
                                         (28, 'bq', 'Bonaire, Sint Eustatius and Saba'),
                                         (29, 'ba', 'Bosnia and Herzegovina'),
                                         (30, 'bw', 'Botswana'),
                                         (31, 'bv', 'Bouvet Island'),
                                         (32, 'br', 'Brazil'),
                                         (33, 'io', 'British Indian Ocean Territory'),
                                         (34, 'bn', 'Brunei Darussalam'),
                                         (35, 'bg', 'Bulgaria'),
                                         (36, 'bf', 'Burkina Faso'),
                                         (37, 'bi', 'Burundi'),
                                         (38, 'kh', 'Cambodia'),
                                         (39, 'cm', 'Cameroon'),
                                         (40, 'ca', 'Canada'),
                                         (41, 'cv', 'Cape Verde'),
                                         (42, 'ky', 'Cayman Islands'),
                                         (43, 'cf', 'Central African Republic'),
                                         (44, 'td', 'Chad'),
                                         (45, 'cl', 'Chile'),
                                         (46, 'cn', 'China'),
                                         (47, 'cx', 'Christmas Island'),
                                         (48, 'cc', 'Cocos(Keeling) Islands'),
                                         (49, 'co', 'Colombia'),
                                         (50, 'km', 'Comoros'),
                                         (51, 'cg', 'Congo'),
                                         (52, 'cd', 'Congo, Democratic Republic of the Congo'),
                                         (53, 'ck', 'Cook Islands'),
                                         (54, 'cr', 'Costa Rica'),
                                         (55, 'ci', 'Cote D''Ivoire'),
                                         (56, 'hr', 'Croatia'),
                                         (57, 'cu', 'Cuba'),
                                         (58, 'cw', 'Curacao'),
                                         (59, 'cy', 'Cyprus'),
                                         (60, 'cz', 'Czech Republic'),
                                         (61, 'dk', 'Denmark'),
                                         (62, 'dj', 'Djibouti'),
                                         (63, 'dm', 'Dominica'),
                                         (64, 'do', 'Dominican Republic'),
                                         (65, 'ec', 'Ecuador'),
                                         (66, 'eg', 'Egypt'),
                                         (67, 'sv', 'El Salvador'),
                                         (68, 'gq', 'Equatorial Guinea'),
                                         (69, 'er', 'Eritrea'),
                                         (70, 'ee', 'Estonia'),
                                         (71, 'et', 'Ethiopia'),
                                         (72, 'fk', 'Falkland Islands(Malvinas)'),
                                         (73, 'fo', 'Faroe Islands'),
                                         (74, 'fj', 'Fiji'),
                                         (75, 'fi', 'Finland'),
                                         (76, 'fr', 'France'),
                                         (77, 'gf', 'French Guiana'),
                                         (78, 'pf', 'French Polynesia'),
                                         (79, 'tf', 'French Southern Territories'),
                                         (80, 'ga', 'Gabon'),
                                         (81, 'gm', 'Gambia'),
                                         (82, 'ge', 'Georgia'),
                                         (83, 'de', 'Germany'),
                                         (84, 'gh', 'Ghana'),
                                         (85, 'gi', 'Gibraltar'),
                                         (86, 'gr', 'Greece'),
                                         (87, 'gl', 'Greenland'),
                                         (88, 'gd', 'Grenada'),
                                         (89, 'gp', 'Guadeloupe'),
                                         (90, 'gu', 'Guam'),
                                         (91, 'gt', 'Guatemala'),
                                         (92, 'gg', 'Guernsey'),
                                         (93, 'gn', 'Guinea'),
                                         (94, 'gw', 'Guinea-Bissau'),
                                         (95, 'gy', 'Guyana'),
                                         (96, 'ht', 'Haiti'),
                                         (97, 'hm', 'Heard Island and Mcdonald Islands'),
                                         (98, 'va', 'Holy See(Vatican City State)'),
                                         (99, 'hn', 'Honduras'),
                                         (100, 'hk', 'Hong Kong'),
                                         (101, 'hu', 'Hungary'),
                                         (102, 'is', 'Iceland'),
                                         (103, 'in', 'India'),
                                         (104, 'id', 'Indonesia'),
                                         (105, 'ir', 'Iran, Islamic Republic of'),
                                         (106, 'iq', 'Iraq'),
                                         (107, 'ie', 'Ireland'),
                                         (108, 'im', 'Isle of Man'),
                                         (109, 'il', 'Israel'),
                                         (110, 'it', 'Italy'),
                                         (111, 'jm', 'Jamaica'),
                                         (112, 'jp', 'Japan'),
                                         (113, 'je', 'Jersey'),
                                         (114, 'jo', 'Jordan'),
                                         (115, 'kz', 'Kazakhstan'),
                                         (116, 'ke', 'Kenya'),
                                         (117, 'ki', 'Kiribati'),
                                         (118, 'kp', 'Korea, Democratic People''s Republic of'),
                                         (119, 'kr', 'Korea, Republic of'),
                                         (120, 'xk', 'Kosovo'),
                                         (121, 'kw', 'Kuwait'),
                                         (122, 'kg', 'Kyrgyzstan'),
                                         (123, 'la', 'Lao People''s Democratic Republic'),
                                         (124, 'lv', 'Latvia'),
                                         (125, 'lb', 'Lebanon'),
                                         (126, 'ls', 'Lesotho'),
                                         (127, 'lr', 'Liberia'),
                                         (128, 'ly', 'Libyan Arab Jamahiriya'),
                                         (129, 'li', 'Liechtenstein'),
                                         (130, 'lt', 'Lithuania'),
                                         (131, 'lu', 'Luxembourg'),
                                         (132, 'mo', 'Macao'),
                                         (133, 'mk', 'Macedonia, the Former Yugoslav Republic of'),
                                         (134, 'mg', 'Madagascar'),
                                         (135, 'mw', 'Malawi'),
                                         (136, 'my', 'Malaysia'),
                                         (137, 'mv', 'Maldives'),
                                         (138, 'ml', 'Mali'),
                                         (139, 'mt', 'Malta'),
                                         (140, 'mh', 'Marshall Islands'),
                                         (141, 'mq', 'Martinique'),
                                         (142, 'mr', 'Mauritania'),
                                         (143, 'mu', 'Mauritius'),
                                         (144, 'yt', 'Mayotte'),
                                         (145, 'mx', 'Mexico'),
                                         (146, 'fm', 'Micronesia, Federated States of'),
                                         (147, 'md', 'Moldova, Republic of'),
                                         (148, 'mc', 'Monaco'),
                                         (149, 'mn', 'Mongolia'),
                                         (150, 'me', 'Montenegro'),
                                         (151, 'ms', 'Montserrat'),
                                         (152, 'ma', 'Morocco'),
                                         (153, 'mz', 'Mozambique'),
                                         (154, 'mm', 'Myanmar'),
                                         (155, 'na', 'Namibia'),
                                         (156, 'nr', 'Nauru'),
                                         (157, 'np', 'Nepal'),
                                         (158, 'nl', 'Netherlands'),
                                         (159, 'an', 'Netherlands Antilles'),
                                         (160, 'nc', 'New Caledonia'),
                                         (161, 'nz', 'New Zealand'),
                                         (162, 'ni', 'Nicaragua'),
                                         (163, 'ne', 'Niger'),
                                         (164, 'ng', 'Nigeria'),
                                         (165, 'nu', 'Niue'),
                                         (166, 'nf', 'Norfolk Island'),
                                         (167, 'mp', 'Northern Mariana Islands'),
                                         (168, 'no', 'Norway'),
                                         (169, 'om', 'Oman'),
                                         (170, 'pk', 'Pakistan'),
                                         (171, 'pw', 'Palau'),
                                         (172, 'ps', 'Palestinian Territory'),
                                         (173, 'pa', 'Panama'),
                                         (174, 'pg', 'Papua New Guinea'),
                                         (175, 'py', 'Paraguay'),
                                         (176, 'pe', 'Peru'),
                                         (177, 'ph', 'Philippines'),
                                         (178, 'pn', 'Pitcairn'),
                                         (179, 'pl', 'Poland'),
                                         (180, 'pt', 'Portugal'),
                                         (181, 'pr', 'Puerto Rico'),
                                         (182, 'qa', 'Qatar'),
                                         (183, 're', 'Reunion'),
                                         (184, 'ro', 'Romania'),
                                         (185, 'ru', 'Russian Federation'),
                                         (186, 'rw', 'Rwanda'),
                                         (187, 'bl', 'Saint Barthelemy'),
                                         (188, 'sh', 'Saint Helena'),
                                         (189, 'kn', 'Saint Kitts and Nevis'),
                                         (190, 'lc', 'Saint Lucia'),
                                         (191, 'mf', 'Saint Martin'),
                                         (192, 'pm', 'Saint Pierre and Miquelon'),
                                         (193, 'vc', 'Saint Vincent and the Grenadines'),
                                         (194, 'ws', 'Samoa'),
                                         (195, 'sm', 'San Marino'),
                                         (196, 'st', 'Sao Tome and Principe'),
                                         (197, 'sa', 'Saudi Arabia'),
                                         (198, 'sn', 'Senegal'),
                                         (199, 'rs', 'Serbia'),
                                         (200, 'cs', 'Serbia and Montenegro'),
                                         (201, 'sc', 'Seychelles'),
                                         (202, 'sl', 'Sierra Leone'),
                                         (203, 'sg', 'Singapore'),
                                         (204, 'sx', 'Sint Maarten'),
                                         (205, 'sk', 'Slovakia'),
                                         (206, 'si', 'Slovenia'),
                                         (207, 'sb', 'Solomon Islands'),
                                         (208, 'so', 'Somalia'),
                                         (209, 'za', 'South Africa'),
                                         (210, 'gs', 'South Georgia and the South Sandwich Islands'),
                                         (211, 'ss', 'South Sudan'),
                                         (212, 'es', 'Spain'),
                                         (213, 'lk', 'Sri Lanka'),
                                         (214, 'sd', 'Sudan'),
                                         (215, 'sr', 'Suriname'),
                                         (216, 'sj', 'Svalbard and Jan Mayen'),
                                         (217, 'sz', 'Swaziland'),
                                         (218, 'se', 'Sweden'),
                                         (219, 'ch', 'Switzerland'),
                                         (220, 'sy', 'Syrian Arab Republic'),
                                         (221, 'tw', 'Taiwan, Province of China'),
                                         (222, 'tj', 'Tajikistan'),
                                         (223, 'tz', 'Tanzania, United Republic of'),
                                         (224, 'th', 'Thailand'),
                                         (225, 'tl', 'Timor-Leste'),
                                         (226, 'tg', 'Togo'),
                                         (227, 'tk', 'Tokelau'),
                                         (228, 'to', 'Tonga'),
                                         (229, 'tt', 'Trinidad and Tobago'),
                                         (230, 'tn', 'Tunisia'),
                                         (231, 'tr', 'Turkey'),
                                         (232, 'tm', 'Turkmenistan'),
                                         (233, 'tc', 'Turks and Caicos Islands'),
                                         (234, 'tv', 'Tuvalu'),
                                         (235, 'ug', 'Uganda'),
                                         (236, 'ua', 'Ukraine'),
                                         (237, 'ae', 'United Arab Emirates'),
                                         (238, 'gb', 'United Kingdom'),
                                         (239, 'us', 'United States'),
                                         (240, 'um', 'United States Minor Outlying Islands'),
                                         (241, 'uy', 'Uruguay'),
                                         (242, 'uz', 'Uzbekistan'),
                                         (243, 'vu', 'Vanuatu'),
                                         (244, 've', 'Venezuela'),
                                         (245, 'vn', 'Viet Nam'),
                                         (246, 'vg', 'Virgin Islands, British'),
                                         (247, 'vi', 'Virgin Islands, U.s.'),
                                         (248, 'wf', 'Wallis and Futuna'),
                                         (249, 'eh', 'Western Sahara'),
                                         (250, 'ye', 'Yemen'),
                                         (251, 'zm', 'Zambia'),
                                         (252, 'zw', 'Zimbabwe');


INSERT INTO speciality(code, value) VALUES ('alrg', 'Allergy and immunology'),
                                        ('anst', 'Anesthesiology'),
                                        ('derma', 'Dermatology'),
                                        ('radio', 'Diagnostic radiology'),
                                        ('emrgn', 'Emergency medicine'),
                                        ('fam', 'Family medicine'),
                                        ('intr', 'Internal medicine'),
                                        ('gntc', 'Medical genetics'),
                                        ('nero', 'Neurology'),
                                        ('nuclr', 'Nuclear medicine'),
                                        ('gynek', 'Obstetrics and gynecology'),
                                        ('optha', 'Ophthalmology'),
                                        ('ptlo', 'Pathology'),
                                        ('pdkt', 'Pediatrics'),
                                        ('phsc', 'Physical medicine and rehabilitation'),
                                        ('prvnt', 'Preventive medicine'),
                                        ('psy','Psychiatry'),
                                        ('onklg', 'Radiation oncology'),
                                        ('srgy', 'Surgery'),
                                        ('urlo', 'Urology');


INSERT INTO public.doctor (id, firstname, gender, lastname, surname, phone, email, availability, birthday, overview) VALUES (1, 'Mohamed', 'MALE', 'STOULI', null, '05 35 40 45 25', null, null, null, null);
INSERT INTO public.doctor (id, firstname, gender, lastname, surname, phone, email, availability, birthday, overview) VALUES (2, 'Hamza', 'MALE', 'KHAFIF', null, null, null, null, null, null);

INSERT INTO public.work_schedule (id, description, doctor_id) VALUES (1, 'Full-time', 1);

INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES ('08:00:00', 'MONDAY', '18:00:00', true, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES ('08:00:00', 'TUESDAY', '18:00:00', true, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES ('08:00:00', 'WEDNESDAY', '18:00:00', true, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES ('08:00:00', 'THURSDAY', '18:00:00', true, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES ('08:00:00', 'FRIDAY', '18:00:00', true, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES (null, 'SUNDAY', null, false, 1);
INSERT INTO work_schedule_opening_hours (closing_time, day, opening_time, opens, work_schedule_id) VALUES (null, 'SATURDAY', null, false, 1);

COMMIT;