INSERT INTO language (id, code, value) VALUES
                                           (1, 'af', 'Afrikaans'),
                                           (2, 'sq', 'Albanian - shqip'),
                                           (3, 'am', 'Amharic - አማርኛ'),
                                           (4, 'ar', 'Arabic - العربية'),
                                           (5, 'an', 'Aragonese - aragonés'),
                                           (6, 'hy', 'Armenian - հայերեն'),
                                           (7, 'ast', 'Asturian - asturianu'),
                                           (8, 'az', 'Azerbaijani - azərbaycan dili'),
                                           (9, 'eu', 'Basque - euskara'),
                                           (10, 'be', 'Belarusian - беларуская'),
                                           (11, 'bn', 'Bengali - বাংলা'),
                                           (12, 'bs', 'Bosnian - bosanski'),
                                           (13, 'br', 'Breton - brezhoneg'),
                                           (14, 'bg', 'Bulgarian - български'),
                                           (15, 'ca', 'Catalan - català'),
                                           (16, 'ckb', 'Central Kurdish - کوردی (دەستنوسی عەرەبی)'),
                                           (17, 'zh', 'Chinese - 中文'),
                                           (18, 'zh-HK', 'Chinese (Hong Kong) - 中文（香港）'),
                                           (19, 'zh-CN', 'Chinese (Simplified) - 中文（简体）'),
                                           (20, 'zh-TW', 'Chinese (Traditional) - 中文（繁體）'),
                                           (21, 'co', 'Corsican'),
                                           (22, 'hr', 'Croatian - hrvatski'),
                                           (23, 'cs', 'Czech - čeština'),
                                           (24, 'da', 'Danish - dansk'),
                                           (25, 'nl', 'Dutch - Nederlands'),
                                           (26, 'en', 'English'),
                                           (27, 'en-AU', 'English (Australia)'),
                                           (28, 'en-CA', 'English (Canada)'),
                                           (29, 'en-IN', 'English (India)'),
                                           (30, 'en-NZ', 'English (New Zealand)'),
                                           (31, 'en-ZA', 'English (South Africa)'),
                                           (32, 'en-GB', 'English (United Kingdom)'),
                                           (33, 'en-US', 'English (United States)'),
                                           (34, 'eo', 'Esperanto - esperanto'),
                                           (35, 'et', 'Estonian - eesti'),
                                           (36, 'fo', 'Faroese - føroyskt'),
                                           (37, 'fil', 'Filipino'),
                                           (38, 'fi', 'Finnish - suomi'),
                                           (39, 'fr', 'French - français'),
                                           (40, 'fr-CA', 'French (Canada) - français (Canada)'),
                                           (41, 'fr-FR', 'French (France) - français (France)'),
                                           (42, 'fr-CH', 'French (Switzerland) - français (Suisse)'),
                                           (43, 'gl', 'Galician - galego'),
                                           (44, 'ka', 'Georgian - ქართული'),
                                           (45, 'de', 'German - Deutsch'),
                                           (46, 'de-AT', 'German (Austria) - Deutsch (Österreich)'),
                                           (47, 'de-DE', 'German (Germany) - Deutsch (Deutschland)'),
                                           (48, 'de-LI', 'German (Liechtenstein) - Deutsch (Liechtenstein)'),
                                           (49, 'de-CH', 'German (Switzerland) - Deutsch (Schweiz)'),
                                           (50, 'el', 'Greek - Ελληνικά'),
                                           (51, 'gn', 'Guarani'),
                                           (52, 'gu', 'Gujarati - ગુજરાતી'),
                                           (53, 'ha', 'Hausa'),
                                           (54, 'haw', 'Hawaiian - ʻŌlelo Hawaiʻi'),
                                           (55, 'he', 'Hebrew - עברית'),
                                           (56, 'hi', 'Hindi - हिन्दी'),
                                           (57, 'hu', 'Hungarian - magyar'),
                                           (58, 'is', 'Icelandic - íslenska'),
                                           (59, 'id', 'Indonesian - Indonesia'),
                                           (60, 'ia', 'Interlingua'),
                                           (61, 'ga', 'Irish - Gaeilge'),
                                           (62, 'it', 'Italian - italiano'),
                                           (63, 'it-IT', 'Italian (Italy) - italiano (Italia)'),
                                           (64, 'it-CH', 'Italian (Switzerland) - italiano (Svizzera)'),
                                           (65, 'ja', 'Japanese - 日本語'),
                                           (66, 'kn', 'Kannada - ಕನ್ನಡ'),
                                           (67, 'kk', 'Kazakh - қазақ тілі'),
                                           (68, 'km', 'Khmer - ខ្មែរ'),
                                           (69, 'ko', 'Korean - 한국어'),
                                           (70, 'ku', 'Kurdish - Kurdî'),
                                           (71, 'ky', 'Kyrgyz - кыргызча'),
                                           (72, 'lo', 'Lao - ລາວ'),
                                           (73, 'la', 'Latin'),
                                           (74, 'lv', 'Latvian - latviešu'),
                                           (75, 'ln', 'Lingala - lingála'),
                                           (76, 'lt', 'Lithuanian - lietuvių'),
                                           (77, 'mk', 'Macedonian - македонски'),
                                           (78, 'ms', 'Malay - Bahasa Melayu'),
                                           (79, 'ml', 'Malayalam - മലയാളം'),
                                           (80, 'mt', 'Maltese - Malti'),
                                           (81, 'mr', 'Marathi - मराठी'),
                                           (82, 'mn', 'Mongolian - монгол'),
                                           (83, 'ne', 'Nepali - नेपाली'),
                                           (84, 'no', 'Norwegian - norsk'),
                                           (85, 'nb', 'Norwegian Bokmål - norsk bokmål'),
                                           (86, 'nn', 'Norwegian Nynorsk - nynorsk'),
                                           (87, 'oc', 'Occitan'),
                                           (88, 'or', 'Oriya - ଓଡ଼ିଆ'),
                                           (89, 'om', 'Oromo - Oromoo'),
                                           (90, 'ps', 'Pashto - پښتو'),
                                           (91, 'fa', 'Persian - فارسی'),
                                           (92, 'pl', 'Polish - polski'),
                                           (93, 'pt', 'Portuguese - português'),
                                           (94, 'pt-BR', 'Portuguese (Brazil) - português (Brasil)'),
                                           (95, 'pt-PT', 'Portuguese (Portugal) - português (Portugal)'),
                                           (96, 'pa', 'Punjabi - ਪੰਜਾਬੀ'),
                                           (97, 'qu', 'Quechua'),
                                           (98, 'ro', 'Romanian - română'),
                                           (99, 'mo', 'Romanian (Moldova) - română (Moldova)'),
                                           (100, 'rm', 'Romansh - rumantsch'),
                                           (101, 'ru', 'Russian - русский'),
                                           (102, 'gd', 'Scottish Gaelic'),
                                           (103, 'sr', 'Serbian - српски'),
                                           (104, 'sh', 'Serbo-Croatian - Srpskohrvatski'),
                                           (105, 'sn', 'Shona - chiShona'),
                                           (106, 'sd', 'Sindhi'),
                                           (107, 'si', 'Sinhala - සිංහල'),
                                           (108, 'sk', 'Slovak - slovenčina'),
                                           (109, 'sl', 'Slovenian - slovenščina'),
                                           (110, 'so', 'Somali - Soomaali'),
                                           (111, 'st', 'Southern Sotho'),
                                           (112, 'es', 'Spanish - español'),
                                           (113, 'es-AR', 'Spanish (Argentina) - español (Argentina)'),
                                           (114, 'es-419', 'Spanish (Latin America) - español (Latinoamérica)'),
                                           (115, 'es-MX', 'Spanish (Mexico) - español (México)'),
                                           (116, 'es-ES', 'Spanish (Spain) - español (España)'),
                                           (117, 'es-US', 'Spanish (United States) - español (Estados Unidos)'),
                                           (118, 'su', 'Sundanese'),
                                           (119, 'sw', 'Swahili - Kiswahili'),
                                           (120, 'sv', 'Swedish - svenska'),
                                           (121, 'tg', 'Tajik - тоҷикӣ'),
                                           (122, 'ta', 'Tamil - தமிழ்'),
                                           (123, 'tt', 'Tatar'),
                                           (124, 'te', 'Telugu - తెలుగు'),
                                           (125, 'th', 'Thai - ไทย'),
                                           (126, 'ti', 'Tigrinya - ትግርኛ'),
                                           (127, 'to', 'Tongan - lea fakatonga'),
                                           (128, 'tr', 'Turkish - Türkçe'),
                                           (129, 'tk', 'Turkmen'),
                                           (130, 'tw', 'Twi'),
                                           (131, 'uk', 'Ukrainian - українська'),
                                           (132, 'ur', 'Urdu - اردو'),
                                           (133, 'ug', 'Uyghur'),
                                           (134, 'uz', 'Uzbek - o‘zbek'),
                                           (135, 'vi', 'Vietnamese - Tiếng Việt'),
                                           (136, 'wa', 'Walloon - wa'),
                                           (137, 'cy', 'Welsh - Cymraeg'),
                                           (138, 'fy', 'Western Frisian'),
                                           (139, 'xh', 'Xhosa'),
                                           (140, 'yi', 'Yiddish'),
                                           (141, 'yo', 'Yoruba - Èdè Yorùbá'),
                                           (142, 'zu', 'Zulu - isiZulu');


INSERT INTO country (id, code, value) VALUES
                                          (1, 'AF', 'Afghanistan'),
                                          (2, 'AX', 'Aland Islands'),
                                          (3, 'AL', 'Albania'),
                                          (4, 'DZ', 'Algeria'),
                                          (5, 'AS', 'American Samoa'),
                                          (6, 'AD', 'Andorra'),
                                          (7, 'AO', 'Angola'),
                                          (8, 'AI', 'Anguilla'),
                                          (9, 'AQ', 'Antarctica'),
                                          (10, 'AG', 'Antigua and Barbuda'),
                                          (11, 'AR', 'Argentina'),
                                          (12, 'AM', 'Armenia'),
                                          (13, 'AW', 'Aruba'),
                                          (14, 'AU', 'Australia'),
                                          (15, 'AT', 'Austria'),
                                          (16, 'AZ', 'Azerbaijan'),
                                          (17, 'BS', 'Bahamas'),
                                          (18, 'BH', 'Bahrain'),
                                          (19, 'BD', 'Bangladesh'),
                                          (20, 'BB', 'Barbados'),
                                          (21, 'BY', 'Belarus'),
                                          (22, 'BE', 'Belgium'),
                                          (23, 'BZ', 'Belize'),
                                          (24, 'BJ', 'Benin'),
                                          (25, 'BM', 'Bermuda'),
                                          (26, 'BT', 'Bhutan'),
                                          (27, 'BO', 'Bolivia'),
                                          (28, 'BQ', 'Bonaire, Sint Eustatius and Saba'),
                                          (29, 'BA', 'Bosnia and Herzegovina'),
                                          (30, 'BW', 'Botswana'),
                                          (31, 'BV', 'Bouvet Island'),
                                          (32, 'BR', 'Brazil'),
                                          (33, 'IO', 'British Indian Ocean Territory'),
                                          (34, 'BN', 'Brunei Darussalam'),
                                          (35, 'BG', 'Bulgaria'),
                                          (36, 'BF', 'Burkina Faso'),
                                          (37, 'BI', 'Burundi'),
                                          (38, 'KH', 'Cambodia'),
                                          (39, 'CM', 'Cameroon'),
                                          (40, 'CA', 'Canada'),
                                          (41, 'CV', 'Cape Verde'),
                                          (42, 'KY', 'Cayman Islands'),
                                          (43, 'CF', 'Central African Republic'),
                                          (44, 'TD', 'Chad'),
                                          (45, 'CL', 'Chile'),
                                          (46, 'CN', 'China'),
                                          (47, 'CX', 'Christmas Island'),
                                          (48, 'CC', 'Cocos (Keeling) Islands'),
                                          (49, 'CO', 'Colombia'),
                                          (50, 'KM', 'Comoros'),
                                          (51, 'CG', 'Congo'),
                                          (52, 'CD', 'Congo, Democratic Republic of the Congo'),
                                          (53, 'CK', 'Cook Islands'),
                                          (54, 'CR', 'Costa Rica'),
                                          (55, 'CI', 'Cote D*Ivoire'),
                                          (56, 'HR', 'Croatia'),
                                          (57, 'CU', 'Cuba'),
                                          (58, 'CW', 'Curacao'),
                                          (59, 'CY', 'Cyprus'),
                                          (60, 'CZ', 'Czech Republic'),
                                          (61, 'DK', 'Denmark'),
                                          (62, 'DJ', 'Djibouti'),
                                          (63, 'DM', 'Dominica'),
                                          (64, 'DO', 'Dominican Republic'),
                                          (65, 'EC', 'Ecuador'),
                                          (66, 'EG', 'Egypt'),
                                          (67, 'SV', 'El Salvador'),
                                          (68, 'GQ', 'Equatorial Guinea'),
                                          (69, 'ER', 'Eritrea'),
                                          (70, 'EE', 'Estonia'),
                                          (71, 'ET', 'Ethiopia'),
                                          (72, 'FK', 'Falkland Islands (Malvinas)'),
                                          (73, 'FO', 'Faroe Islands'),
                                          (74, 'FJ', 'Fiji'),
                                          (75, 'FI', 'Finland'),
                                          (76, 'FR', 'France'),
                                          (77, 'GF', 'French Guiana'),
                                          (78, 'PF', 'French Polynesia'),
                                          (79, 'TF', 'French Southern Territories'),
                                          (80, 'GA', 'Gabon'),
                                          (81, 'GM', 'Gambia'),
                                          (82, 'GE', 'Georgia'),
                                          (83, 'DE', 'Germany'),
                                          (84, 'GH', 'Ghana'),
                                          (85, 'GI', 'Gibraltar'),
                                          (86, 'GR', 'Greece'),
                                          (87, 'GL', 'Greenland'),
                                          (88, 'GD', 'Grenada'),
                                          (89, 'GP', 'Guadeloupe'),
                                          (90, 'GU', 'Guam'),
                                          (91, 'GT', 'Guatemala'),
                                          (92, 'GG', 'Guernsey'),
                                          (93, 'GN', 'Guinea'),
                                          (94, 'GW', 'Guinea-Bissau'),
                                          (95, 'GY', 'Guyana'),
                                          (96, 'HT', 'Haiti'),
                                          (97, 'HM', 'Heard Island and Mcdonald Islands'),
                                          (98, 'VA', 'Holy See (Vatican City State)'),
                                          (99, 'HN', 'Honduras'),
                                          (100, 'HK', 'Hong Kong'),
                                          (101, 'HU', 'Hungary'),
                                          (102, 'IS', 'Iceland'),
                                          (103, 'IN', 'India'),
                                          (104, 'ID', 'Indonesia'),
                                          (105, 'IR', 'Iran, Islamic Republic of'),
                                          (106, 'IQ', 'Iraq'),
                                          (107, 'IE', 'Ireland'),
                                          (108, 'IM', 'Isle of Man'),
                                          (109, 'IL', 'Israel'),
                                          (110, 'IT', 'Italy'),
                                          (111, 'JM', 'Jamaica'),
                                          (112, 'JP', 'Japan'),
                                          (113, 'JE', 'Jersey'),
                                          (114, 'JO', 'Jordan'),
                                          (115, 'KZ', 'Kazakhstan'),
                                          (116, 'KE', 'Kenya'),
                                          (117, 'KI', 'Kiribati'),
                                          (118, 'KP', 'Korea, Democratic People*s Republic of'),
                                          (119, 'KR', 'Korea, Republic of'),
                                          (120, 'XK', 'Kosovo'),
                                          (121, 'KW', 'Kuwait'),
                                          (122, 'KG', 'Kyrgyzstan'),
                                          (123, 'LA', 'Lao People*s Democratic Republic'),
                                          (124, 'LV', 'Latvia'),
                                          (125, 'LB', 'Lebanon'),
                                          (126, 'LS', 'Lesotho'),
                                          (127, 'LR', 'Liberia'),
                                          (128, 'LY', 'Libyan Arab Jamahiriya'),
                                          (129, 'LI', 'Liechtenstein'),
                                          (130, 'LT', 'Lithuania'),
                                          (131, 'LU', 'Luxembourg'),
                                          (132, 'MO', 'Macao'),
                                          (133, 'MK', 'Macedonia, the Former Yugoslav Republic of'),
                                          (134, 'MG', 'Madagascar'),
                                          (135, 'MW', 'Malawi'),
                                          (136, 'MY', 'Malaysia'),
                                          (137, 'MV', 'Maldives'),
                                          (138, 'ML', 'Mali'),
                                          (139, 'MT', 'Malta'),
                                          (140, 'MH', 'Marshall Islands'),
                                          (141, 'MQ', 'Martinique'),
                                          (142, 'MR', 'Mauritania'),
                                          (143, 'MU', 'Mauritius'),
                                          (144, 'YT', 'Mayotte'),
                                          (145, 'MX', 'Mexico'),
                                          (146, 'FM', 'Micronesia, Federated States of'),
                                          (147, 'MD', 'Moldova, Republic of'),
                                          (148, 'MC', 'Monaco'),
                                          (149, 'MN', 'Mongolia'),
                                          (150, 'ME', 'Montenegro'),
                                          (151, 'MS', 'Montserrat'),
                                          (152, 'MA', 'Morocco'),
                                          (153, 'MZ', 'Mozambique'),
                                          (154, 'MM', 'Myanmar'),
                                          (155, 'NA', 'Namibia'),
                                          (156, 'NR', 'Nauru'),
                                          (157, 'NP', 'Nepal'),
                                          (158, 'NL', 'Netherlands'),
                                          (159, 'AN', 'Netherlands Antilles'),
                                          (160, 'NC', 'New Caledonia'),
                                          (161, 'NZ', 'New Zealand'),
                                          (162, 'NI', 'Nicaragua'),
                                          (163, 'NE', 'Niger'),
                                          (164, 'NG', 'Nigeria'),
                                          (165, 'NU', 'Niue'),
                                          (166, 'NF', 'Norfolk Island'),
                                          (167, 'MP', 'Northern Mariana Islands'),
                                          (168, 'NO', 'Norway'),
                                          (169, 'OM', 'Oman'),
                                          (170, 'PK', 'Pakistan'),
                                          (171, 'PW', 'Palau'),
                                          (172, 'PS', 'Palestinian Territory'),
                                          (173, 'PA', 'Panama'),
                                          (174, 'PG', 'Papua New Guinea'),
                                          (175, 'PY', 'Paraguay'),
                                          (176, 'PE', 'Peru'),
                                          (177, 'PH', 'Philippines'),
                                          (178, 'PN', 'Pitcairn'),
                                          (179, 'PL', 'Poland'),
                                          (180, 'PT', 'Portugal'),
                                          (181, 'PR', 'Puerto Rico'),
                                          (182, 'QA', 'Qatar'),
                                          (183, 'RE', 'Reunion'),
                                          (184, 'RO', 'Romania'),
                                          (185, 'RU', 'Russian Federation'),
                                          (186, 'RW', 'Rwanda'),
                                          (187, 'BL', 'Saint Barthelemy'),
                                          (188, 'SH', 'Saint Helena'),
                                          (189, 'KN', 'Saint Kitts and Nevis'),
                                          (190, 'LC', 'Saint Lucia'),
                                          (191, 'MF', 'Saint Martin'),
                                          (192, 'PM', 'Saint Pierre and Miquelon'),
                                          (193, 'VC', 'Saint Vincent and the Grenadines'),
                                          (194, 'WS', 'Samoa'),
                                          (195, 'SM', 'San Marino'),
                                          (196, 'ST', 'Sao Tome and Principe'),
                                          (197, 'SA', 'Saudi Arabia'),
                                          (198, 'SN', 'Senegal'),
                                          (199, 'RS', 'Serbia'),
                                          (200, 'CS', 'Serbia and Montenegro'),
                                          (201, 'SC', 'Seychelles'),
                                          (202, 'SL', 'Sierra Leone'),
                                          (203, 'SG', 'Singapore'),
                                          (204, 'SX', 'Sint Maarten'),
                                          (205, 'SK', 'Slovakia'),
                                          (206, 'SI', 'Slovenia'),
                                          (207, 'SB', 'Solomon Islands'),
                                          (208, 'SO', 'Somalia'),
                                          (209, 'ZA', 'South Africa'),
                                          (210, 'GS', 'South Georgia and the South Sandwich Islands'),
                                          (211, 'SS', 'South Sudan'),
                                          (212, 'ES', 'Spain'),
                                          (213, 'LK', 'Sri Lanka'),
                                          (214, 'SD', 'Sudan'),
                                          (215, 'SR', 'Suriname'),
                                          (216, 'SJ', 'Svalbard and Jan Mayen'),
                                          (217, 'SZ', 'Swaziland'),
                                          (218, 'SE', 'Sweden'),
                                          (219, 'CH', 'Switzerland'),
                                          (220, 'SY', 'Syrian Arab Republic'),
                                          (221, 'TW', 'Taiwan, Province of China'),
                                          (222, 'TJ', 'Tajikistan'),
                                          (223, 'TZ', 'Tanzania, United Republic of'),
                                          (224, 'TH', 'Thailand'),
                                          (225, 'TL', 'Timor-Leste'),
                                          (226, 'TG', 'Togo'),
                                          (227, 'TK', 'Tokelau'),
                                          (228, 'TO', 'Tonga'),
                                          (229, 'TT', 'Trinidad and Tobago'),
                                          (230, 'TN', 'Tunisia'),
                                          (231, 'TR', 'Turkey'),
                                          (232, 'TM', 'Turkmenistan'),
                                          (233, 'TC', 'Turks and Caicos Islands'),
                                          (234, 'TV', 'Tuvalu'),
                                          (235, 'UG', 'Uganda'),
                                          (236, 'UA', 'Ukraine'),
                                          (237, 'AE', 'United Arab Emirates'),
                                          (238, 'GB', 'United Kingdom'),
                                          (239, 'US', 'United States'),
                                          (240, 'UM', 'United States Minor Outlying Islands'),
                                          (241, 'UY', 'Uruguay'),
                                          (242, 'UZ', 'Uzbekistan'),
                                          (243, 'VU', 'Vanuatu'),
                                          (244, 'VE', 'Venezuela'),
                                          (245, 'VN', 'Viet Nam'),
                                          (246, 'VG', 'Virgin Islands, British'),
                                          (247, 'VI', 'Virgin Islands, U.s.'),
                                          (248, 'WF', 'Wallis and Futuna'),
                                          (249, 'EH', 'Western Sahara'),
                                          (250, 'YE', 'Yemen'),
                                          (251, 'ZM', 'Zambia'),
                                          (252, 'ZW', 'Zimbabwe');
